# Generated by Django 4.1 on 2022-10-11 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='phone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Country', models.CharField(max_length=100)),
                ('State', models.CharField(max_length=100)),
                ('Mobile', models.ManyToManyField(to='relationmtom.phone')),
            ],
        ),
        migrations.CreateModel(
            name='aadar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aName', models.CharField(max_length=100)),
                ('anumber', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('Mobile', models.ManyToManyField(to='relationmtom.phone')),
            ],
        ),
    ]
