# Generated by Django 4.1 on 2022-10-11 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('relationotom', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aadar',
            old_name='Country',
            new_name='aName',
        ),
        migrations.RenameField(
            model_name='aadar',
            old_name='Name',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='aadar',
            old_name='State',
            new_name='anumber',
        ),
    ]
