# Generated by Django 4.1 on 2022-10-12 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relationotom', '0002_rename_country_aadar_aname_rename_name_aadar_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='phone',
            name='email',
            field=models.EmailField(default='GFG is best', max_length=250),
        ),
    ]
