# Generated by Django 4.1 on 2022-10-09 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employeeapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='employee',
            name='Vehicle',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='employeeapi.vehicle'),
        ),
    ]
